services:
    app:
        image: scrap:latest
        # build:
        #     context: .
        #     dockerfile: Dockerfile
        ports:
            - '3000:3000'
        hostname: scrapbazaar-backend
        environment:
            - NODE_ENV=production
            - DB_STRING=mongodb://mongo.prv:27017
        # volumes:
        #     - .:/home/node/source
        extra_hosts:
            - mongo.prv:192.168.1.104
